# Generated by Django 5.0 on 2024-02-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_plant_trackingstage_trackingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='trackingevent',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='trackingevent',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='trackingevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='TrackingStage',
        ),
        migrations.DeleteModel(
            name='TrackingEvent',
        ),
    ]
