# Generated by Django 5.0 on 2024-02-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cropstage_remove_trackingevent_plant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CropStage',
            new_name='CropLifeStage',
        ),
    ]
