# Generated by Django 5.0 on 2024-02-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_cropstage_croplifestage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croplifestage',
            name='completed',
        ),
        migrations.CreateModel(
            name='CropLifeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.croplifestage')),
            ],
        ),
    ]
