# Generated by Django 5.0 on 2024-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_croplifestage_completed_croplifetracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croplifetracker',
            name='stage',
        ),
        migrations.RenameField(
            model_name='croplifetracker',
            old_name='completed',
            new_name='delivered',
        ),
        migrations.AddField(
            model_name='croplifetracker',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='croplifetracker',
            name='out_for_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='croplifetracker',
            name='plant_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='croplifetracker',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='croplifetracker',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CropLifeStage',
        ),
    ]
