# Generated by Django 5.0 on 2024-02-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_croplifetracker_stage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croplifetracker',
            old_name='delivered',
            new_name='Buy_Seeds_or_Saplings',
        ),
        migrations.RenameField(
            model_name='croplifetracker',
            old_name='order_placed',
            new_name='adding_manure_and_fertilizers',
        ),
        migrations.RenameField(
            model_name='croplifetracker',
            old_name='out_for_delivery',
            new_name='harvesting_and_storage',
        ),
        migrations.RenameField(
            model_name='croplifetracker',
            old_name='processing',
            new_name='irrigation',
        ),
        migrations.RenameField(
            model_name='croplifetracker',
            old_name='shipped',
            new_name='preparation_of_soil_sowing',
        ),
    ]
