# Generated by Django 5.0 on 2024-02-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_delivered_croplifetracker_buy_seeds_or_saplings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croplifetracker',
            old_name='Buy_Seeds_or_Saplings',
            new_name='buy_seeds_or_saplings',
        ),
    ]
