# Generated by Django 5.0 on 2024-02-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_buy_seeds_or_saplings_croplifetracker_buy_seeds_or_saplings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='date_added',
        ),
    ]
