# Generated by Django 5.0 on 2024-02-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_cartitem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_price',
        ),
    ]
